# Generated by Django 4.1.1 on 2022-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_alter_testflowtool_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattempt',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
